<$ROOT/src/mkhdr

TARG=kernel.bin

CFLAGS=\
	-ffreestanding\
	-nostdlib\
	-O2\
	-Wall\
	-Wextra\

LDFLAGS=\
	-T linker.ld\

HFILES=\
	tty.h\
	gdt.h\
	pager.h\

OFILES=\
	_start.$O\
	entry.$O\
	tty.$O\
	gdt.$O\
	pager.$O\

<$ROOT/src/mkone
